codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "**/example/"
  - "examples"
  - "**/*.g.dart"
  - "**/*.gr.dart"
  - "**/*.freezed.dart"
  - "**/*.retrofit.dart"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false